### ISSUE TITLE
Latest version not compiling

### ISSUE THREAD

**Issue by cmfrancis** [sparkfun/SparkFun_SCD30_Arduino_Library#10]
Latest release is giving this error in Arduino 1.8.10 when compiling for the Uno:

Documents\Arduino\libraries\SparkFun_SCD30_Arduino_Library-master\src\SparkFun_SCD30_Arduino_Library.cpp:257:12: error: 'class HardwareSerial' has no member named 'printf'; did you mean 'print'?
Multiple libraries were found for "Wire.h"

Arduino 1.8.11 doesn't have the Wire.h error but still has the printf error.

**Comment by xvilajosana** [comment]
same error found. Could you please fix?

**Comment by nseidle** [comment]
Sorry. [This PR](https://github.com/sparkfun/SparkFun_SCD30_Arduino_Library/pull/7) broke it.

Offending Serial.prints removed. Now compiles for Uno.
