### ISSUE TITLE
Redundant options in Example2_SetOptions.ino

### ISSUE THREAD

**Issue by alfkoehn** [sparkfun/SparkFun_SCD30_Arduino_Library#15]
In the file `examples/Example2_SetOptions/Example2_SetOptions.ino`, there are both, `airSensor.setAltitudeCompensation()` and `airSensor.setAmbientPressure()` performed. The document _Interface Description Sensirion SCD30 Sensor Module_ from Sensirion, however, states that _Setting altitude is disregarded when an ambient pressure is given to the sensor_ (Section 1.4.8)

One could maybe add this information as a comment to the file `Example2_SetOptions.ino`

**Comment by nseidle** [comment]
Thanks to @awatterott, some new comments have been added. Please review and re-open if they are not sufficient.
