### ISSUE TITLE
Disable ASC (Auto Self Calibration) per default

### ISSUE THREAD

**Issue by ghost** [sparkfun/SparkFun_SCD30_Arduino_Library#22]
According to the documentation ([chapter 1.3.6](https://cdn.sparkfun.com/assets/d/c/0/7/2/SCD30_Interface_Description.pdf)) ASC is disabled by default in the sensor. 

I think it is verry misleading, when the library will turn it on by default. 
When not specifing anything else, it should behave like documenated by SENSIRION. 

https://github.com/sparkfun/SparkFun_SCD30_Arduino_Library/blob/42f08eb1078743ef1b5abe612ddbed4bc12376c5/src/SparkFun_SCD30_Arduino_Library.h#L72-L74

**Comment by nseidle** [comment]
Agreed. Removing.

**Comment by nseidle** [comment]
Should be [done](https://github.com/sparkfun/SparkFun_SCD30_Arduino_Library/releases/tag/v1.0.12).
