### ISSUE TITLE
SCD30 Temperature offset library isn't working 

### ISSUE THREAD

**Issue by IshwariyaVen** [sparkfun/SparkFun_SCD30_Arduino_Library#25]
Hi Team, 

I have been recently working with SCD30 and found there was a difference in the measured and actual Temperature and CO2 of the environment as I used a precise measuring unit to measure reference readings (which is LICOR LI_6800). 

I then tried to force calibrate SCD30 for CO2 with the use of Arduino board, and used the example code given in the github for CO2 force calibration, which worked well. 

But when I tried to do the same with example given in github for Temperature offset, but it's not working as intended. Even after , setting the offset value, the reading measurement of SCD30 is same as before off-setting. 

Could anyone please help me out on this? Any help or leads will be highly appreciated. 

Thanks in advance!

**Comment by physikant** [comment]
Temperature compensation is working for me with library version 1.0.13.
I adapted the code from the example:
airSensor.setTemperatureOffset(2); 

Serial.print("Current temperature offset: ");
Serial.print(airSensor.getTemperatureOffset(), 2);
Serial.println("\u00b0C");

The output temperature is definitely adjusted properly in my case.

**Comment by nseidle** [comment]
Hi @IshwariyaVen - Do you have some minimal code that demonstrates the issue? Like physikant, I can't replicate.

**Comment by IshwariyaVen** [comment]
@physikant, Thank you for the response with additional information on the version. 

@nseidle, Many thanks for following up for the issue. 

I noticed that I was using version 1.0.12. After, @physikant mentioned about the version I updated the version to 1.0.14 and the code worked.  

Reference Code snippet:

```
#include <SparkFun_SCD30_Arduino_Library.h>
#include <Wire.h>
SCD30 airSensor;
void setup()
{
  Serial.begin(9600);
  Wire.begin();
  airSensor.setTemperatureOffset(5.3);     //Temp. in deg. C to offset
  float offset = airSensor.getTemperatureOffset();
  Serial.print("Current temp offset: ");
  Serial.print(offset, 3);
}  
```

**Comment by nseidle** [comment]
Glad to hear it!

**Comment by patfelst** [comment]
Hi there, thanks for this library. I am using it on a M5 Stack Core2 (ESP32) and things are working ok, except for the temperature offset. When I set a positive offset of, there is no change to the temperature reading. If I set a negative offset, I get incorrect temperature readings. Setting the offset back to zero in the same program, the temperature then slowly begins to climb back to its correct value. Here is the test code I used to demonstrate this:

```C++
void scd30_temp_offset(float temp_offs) {
  airSensor.setTemperatureOffset(temp_offs);
  while (!airSensor.dataAvailable());
  Serial.printf("Set temp offset = %.2f, Temperature %.2f, get temp offset %.3f\n",
                temp_offs, airSensor.getTemperature(), airSensor.getTemperatureOffset());
}

void scd30_read_temp(void) {
  while (!airSensor.dataAvailable());
  Serial.printf("Temperature %.2f, get temp offset %.3f\n", airSensor.getTemperature(), airSensor.getTemperatureOffset());
}

void setup(void) {
  M5.begin(true, false, true, true, false);  // Start M5 Stack Core2
  M5.Axp.SetLed(0);                          // Turn off green LED

  Wire.begin(32, 33);  // Start I2C for CO2 sensor. Using I2C pins SDA = 32, SCL = 33
  airSensor.begin();   // Start Sensirion SCD-30 CO2 sensor
  delay(100);
  scd30_temp_offset(0.0);
  scd30_temp_offset(1.0);
  scd30_temp_offset(2.0);
  scd30_temp_offset(3.0);
  scd30_temp_offset(2.0);
  scd30_temp_offset(1.0);
  scd30_temp_offset(0.5);
  scd30_temp_offset(0.0);
  scd30_temp_offset(-0.5);
  scd30_temp_offset(-1.0);
  scd30_temp_offset(-2.0);
  scd30_temp_offset(-3.0);
  scd30_temp_offset(0.0);

  for (uint16_t i = 0; i < 15; i++) {
    scd30_read_temp();
  }
}
```
which outputs the following:
```
Set temp offset = 0.00, Temperature 21.45, get temp offset 0.000
Set temp offset = 1.00, Temperature 21.51, get temp offset 1.000
Set temp offset = 2.00, Temperature 21.52, get temp offset 2.000
Set temp offset = 3.00, Temperature 21.60, get temp offset 3.000
Set temp offset = 2.00, Temperature 21.61, get temp offset 2.000
Set temp offset = 1.00, Temperature 21.68, get temp offset 1.000
Set temp offset = 0.50, Temperature 21.74, get temp offset 0.500
Set temp offset = 0.00, Temperature 21.81, get temp offset 0.000
Set temp offset = -0.50, Temperature 14.67, get temp offset 654.860
Set temp offset = -1.00, Temperature 7.60, get temp offset 654.360
Set temp offset = -2.00, Temperature 0.65, get temp offset 653.360
Set temp offset = -3.00, Temperature -6.23, get temp offset 652.360
Set temp offset = 0.00, Temperature -5.85, get temp offset 0.000
Temperature -5.47, get temp offset 0.000
Temperature -5.13, get temp offset 0.000
Temperature -4.74, get temp offset 0.000
Temperature -4.37, get temp offset 0.000
Temperature -4.02, get temp offset 0.000
Temperature -3.68, get temp offset 0.000
Temperature -3.32, get temp offset 0.000
Temperature -2.98, get temp offset 0.000
Temperature -2.64, get temp offset 0.000
Temperature -2.30, get temp offset 0.000
Temperature -1.97, get temp offset 0.000
Temperature -1.64, get temp offset 0.000
Temperature -1.32, get temp offset 0.000
Temperature -1.00, get temp offset 0.000
Temperature -0.67, get temp offset 0.000
```
I read on [another SCD30 library](https://github.com/paulvha/scd30/blob/6afe3e6c1eb0ec7eb6f9df9657eb8c9566b6a535/src/paulvha_SCD30.cpp#L338) that the device cannot accept a negative offset.

Am I doing something wrong, or is there a problem with the library? I think it will be easier for me to code my own offset after the temperature reading, I just thought I'd let you know about this.
