### ISSUE TITLE
getMeasurementInterval() is not implemented!

### ISSUE THREAD

**Issue by physikant** [sparkfun/SparkFun_SCD30_Arduino_Library#26]
I noticed that the getMeasurementInterval() function is not implemented.
I'm not an experienced C programmer, but I managed to implement it myself by adding
"uint16_t getMeasurementInterval(void); "
on line 96 of the header file and adding
"//Get the measurement interval. See 1.3.8.
uint16_t SCD30::getMeasurementInterval(void)
{
  return readRegister(COMMAND_SET_MEASUREMENT_INTERVAL);
}"
to the cpp file.

**Comment by nseidle** [comment]
[It is](https://github.com/sparkfun/SparkFun_SCD30_Arduino_Library/blob/main/src/SparkFun_SCD30_Arduino_Library.h#L87) already implemented, but a helper function would be nice. I'll see what I can do.

**Comment by nseidle** [comment]
Checkout ex 2 in the latest release. Please let us know if you have problems.

**Comment by physikant** [comment]
Great, it is working for me. Thanks a lot!

**Comment by nseidle** [comment]
Good to hear!
