### ISSUE TITLE
how to know if only one sensor is not working ?

### ISSUE THREAD

**Issue by matthieu4294967296moineau** [sparkfun/SparkFun_SCD30_Arduino_Library#28]
Hello,

If the scd30 is not properly wired, then the function `airSensor.begin()` will return false, same for `airSensor.dataAvailable()` if it was disconnected after being initialised.

But if only 1 from the 3 sensors (co2, temperature, humidity) stops working, how can I know it ?

Because when calling `airSensor.dataAvailable()`, it will still return true for the 2 remaining sensors, and if I call `airSensor.getCO2()` (if it is the co2 sensor that is broken), I will get the same value over and over.

Thank you

**Comment by nseidle** [comment]
Hi - The SCD30 has only one allowed I2C address so you must either use a [Qwiic mux](https://www.sparkfun.com/products/16784) or a device with multiple I2C buses (not many have 2, very few have 3). Assuming you're using a mux, you'll switch between channels and create a sensor for each channel (airSensor1, airSensor2, etc). Each sensor will have its own airSensor1.dataAvailable(), airSensor2.dataAvailable() that will return true/false. If I was concerned about if the sensor was still answering, I would have a timeout that, once crossed, marked the sensor as non-functional. I hope this helps clarify things a bit!

As this is not a problem with the library, if you need more help, I recommend posting to the [support forums](https://forum.sparkfun.com/).
