### ISSUE TITLE
ASC success/failure?

### ISSUE THREAD

**Issue by rhscdn** [sparkfun/SparkFun_SCD30_Arduino_Library#31]
This isn't really an issue with the library but I may am confused regarding the SD30 ASC self-calibration. The documentation seems sparse and the library example code seems limited. What is the expected result after waiting 7 days and dutifully exposing the sensor to fresh winter air for 1hr/day? How does one tell if or when the ASC value has been updated? Can the value be queried?

**Comment by nseidle** [comment]
I don't mean to pass the buck, but we have no internal knowledge of how the SCD30 sensor works. Your best bet is to ping [Sensirion](https://github.com/Sensirion). I don't see a SCD3x specific repo but the [SCD4x](https://github.com/Sensirion/arduino-i2c-scd4x/issues) might be a good place ask.
